project: ax360-frontend-staging            # Translates to a GCP Project 
infraVersion: 0.1.x                        # NEXT
domain: staging.frontend.ax360.ia-gcp.com  # Root CNAME for all workload deployed in the GCP project
sharedVpc: ax360-prod                      # Reference to the shared VPC