infraBaseline: lts                           # lts
terraformVars:                               # Terraform variables
  project: ax360-frontend-staging            # Translates to a GCP Project 
  domain: staging.frontend.ax360.ia-gcp.com  # Root CNAME for all workload deployed in the GCP project
  sharedVpc: ax360-staging                   # Reference to the shared VPC